# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lisa < Formula
  desc "tmux orchestrator for Claude/Codex AI agent sessions."
  homepage "https://github.com/bma-d/lisa"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bma-d/lisa/releases/download/v1.2.1/lisa_1.2.1_darwin_amd64.tar.gz"
      sha256 "ed615eff4e4dd94385bba8c91101d299ccac4da7ebb4c0138588b21ec046008a"

      def install
        bin.install "lisa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bma-d/lisa/releases/download/v1.2.1/lisa_1.2.1_darwin_arm64.tar.gz"
      sha256 "db048db5b35d4dd0c4df0d92d14440e17078852f1dfc5710eb8ad5b6f141ee6d"

      def install
        bin.install "lisa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bma-d/lisa/releases/download/v1.2.1/lisa_1.2.1_linux_amd64.tar.gz"
      sha256 "386ba83a39a6b1b121c61bc0d2dd6b2c9264adabf56f1459ce7dd4ccdc929fbf"
      def install
        bin.install "lisa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bma-d/lisa/releases/download/v1.2.1/lisa_1.2.1_linux_arm64.tar.gz"
      sha256 "0a7e419e43dbba99b82c111f426d29449890864c9179ef3c74bc5390780bb9e3"
      def install
        bin.install "lisa"
      end
    end
  end

  test do
    system "#{bin}/lisa", "version"
  end
end
