# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lisa < Formula
  desc "tmux orchestrator for Claude/Codex AI agent sessions."
  homepage "https://github.com/bma-d/lisa"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bma-d/lisa/releases/download/v1.0.1/lisa_1.0.1_darwin_amd64.tar.gz"
      sha256 "8b1c7dbd29750e8e6fc5d3bd1979c92b5dc13c4e5a01679e3ccdd92bdf379dfd"

      def install
        bin.install "lisa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bma-d/lisa/releases/download/v1.0.1/lisa_1.0.1_darwin_arm64.tar.gz"
      sha256 "20f19aba8647c81571b1af4c0ae2fa6a31f2a37b409e24a405c76f99d4d32ba5"

      def install
        bin.install "lisa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bma-d/lisa/releases/download/v1.0.1/lisa_1.0.1_linux_amd64.tar.gz"
      sha256 "f3d82636eef3b94813445d3e6ea3535c712dc09b4dd95172352a1531cdf5258e"
      def install
        bin.install "lisa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bma-d/lisa/releases/download/v1.0.1/lisa_1.0.1_linux_arm64.tar.gz"
      sha256 "a17de66d3b42f369604e9764b11b43ce264245496fde698eed35859a7cb08a90"
      def install
        bin.install "lisa"
      end
    end
  end

  test do
    system "#{bin}/lisa", "version"
  end
end
