# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmuxVisualiser < Formula
  desc "Live tmux session visualiser for your terminal."
  homepage "https://github.com/bma-d/tmux-visualiser"
  version "1.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bma-d/tmux-visualiser/releases/download/v1.2.2/tmux-visualiser_1.2.2_darwin_amd64.tar.gz"
      sha256 "d81bce6b35a85b14ac871cba458e6e69407e41a0b729308be0fe31e34bfbcfa4"

      define_method(:install) do
        bin.install "tmux-visualiser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bma-d/tmux-visualiser/releases/download/v1.2.2/tmux-visualiser_1.2.2_darwin_arm64.tar.gz"
      sha256 "156c90a402fa13e91aa76098db86e1b0b0cd0ff3b7938e6c2bbe0887df141abc"

      define_method(:install) do
        bin.install "tmux-visualiser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bma-d/tmux-visualiser/releases/download/v1.2.2/tmux-visualiser_1.2.2_linux_amd64.tar.gz"
      sha256 "e91542fc064546c18525d5881398f774c02afb0fbf13311ad7b79b96421c4416"
      define_method(:install) do
        bin.install "tmux-visualiser"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bma-d/tmux-visualiser/releases/download/v1.2.2/tmux-visualiser_1.2.2_linux_arm64.tar.gz"
      sha256 "97b1b1251701c68ae149daac2f2b63982ddd9628cc5eadc57a7dae762a055b14"
      define_method(:install) do
        bin.install "tmux-visualiser"
      end
    end
  end

  test do
    system "#{bin}/tmux-visualiser", "-version"
  end
end
